# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 812775be5a36d08f2c7c16dba41ff5aa9a738b805ac3bfb8bcd2dd4ed787acdfd051a275bdc3980c3bf50f5ca09f1d01e2d00b6a14c3229e848c3fe2dcad3d2d

test:
  secret_key_base: 74f6cc140bb77c5b22dcab3304df10765af430a477fd6ae6278de2f38452f5d1c64833d1617006e75e3b79848fa4ed61148336f60042d084ecfb32e2bc67c43c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
